# configs/config.yaml
server:
  port: 8080
  mode: debug

mysql:
  host: localhost
  port: 3306
  username: root
  password: Root@123456
  database: seckill
  charset: utf8mb4

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0